/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) spline_bicycle_model_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {5, 5, 1};
static const casadi_int casadi_s2[3] = {5, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {8, 1, 1};
static const casadi_int casadi_s5[3] = {7, 1, 1};
static const casadi_int casadi_s6[3] = {28, 1, 1};

/* spline_bicycle_model_expl_ode_hess:(i0[5],i1[5x5],i2[5x2],i3[5],i4[2],i5[8])->(o0[7],o1[28]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][3] : 0;
  a04=arg[3]? arg[3][1] : 0;
  a05=(a03*a04);
  a06=(a02*a05);
  a01=sin(a01);
  a07=arg[3]? arg[3][0] : 0;
  a08=(a03*a07);
  a09=(a01*a08);
  a06=(a06-a09);
  if (res[0]!=0) res[0][2]=a06;
  a06=arg[3]? arg[3][4] : 0;
  a09=(a03+a03);
  a10=2.9999999999999999e-01;
  a11=2.0000000000000000e-03;
  a12=arg[3]? arg[3][3] : 0;
  a11=(a11*a12);
  a10=(a10*a11);
  a09=(a09*a10);
  a06=(a06-a09);
  a09=6.3856960408684549e-01;
  a11=arg[4]? arg[4][0] : 0;
  a13=tan(a11);
  a14=arg[3]? arg[3][2] : 0;
  a13=(a13*a14);
  a13=(a09*a13);
  a06=(a06+a13);
  a13=(a01*a04);
  a06=(a06+a13);
  a13=(a02*a07);
  a06=(a06+a13);
  if (res[0]!=0) res[0][3]=a06;
  if (res[0]!=0) res[0][4]=a00;
  a00=1.5660000000000001e+00;
  a03=(a03/a00);
  a03=(a03*a14);
  a00=cos(a11);
  a06=casadi_sq(a00);
  a03=(a03/a06);
  if (res[0]!=0) res[0][5]=a03;
  if (res[0]!=0) res[0][6]=a12;
  a12=arg[1]? arg[1][2] : 0;
  a13=arg[1]? arg[1][3] : 0;
  a15=(a04*a13);
  a15=(a02*a15);
  a16=(a01*a12);
  a17=(a05*a16);
  a15=(a15-a17);
  a17=(a02*a12);
  a18=(a08*a17);
  a19=(a07*a13);
  a19=(a01*a19);
  a18=(a18+a19);
  a15=(a15-a18);
  a12=(a12*a15);
  a17=(a04*a17);
  a18=(a13+a13);
  a18=(a10*a18);
  a17=(a17-a18);
  a16=(a07*a16);
  a17=(a17-a16);
  a16=(a13*a17);
  a12=(a12+a16);
  if (res[1]!=0) res[1][0]=a12;
  a12=arg[1]? arg[1][7] : 0;
  a16=(a12*a15);
  a18=arg[1]? arg[1][8] : 0;
  a19=(a18*a17);
  a16=(a16+a19);
  if (res[1]!=0) res[1][1]=a16;
  a16=arg[1]? arg[1][12] : 0;
  a19=(a16*a15);
  a20=arg[1]? arg[1][13] : 0;
  a21=(a20*a17);
  a19=(a19+a21);
  if (res[1]!=0) res[1][2]=a19;
  a19=arg[1]? arg[1][17] : 0;
  a21=(a19*a15);
  a22=arg[1]? arg[1][18] : 0;
  a23=(a22*a17);
  a21=(a21+a23);
  if (res[1]!=0) res[1][3]=a21;
  a21=arg[1]? arg[1][22] : 0;
  a23=(a21*a15);
  a24=arg[1]? arg[1][23] : 0;
  a25=(a24*a17);
  a23=(a23+a25);
  if (res[1]!=0) res[1][4]=a23;
  a23=arg[2]? arg[2][2] : 0;
  a25=(a23*a15);
  a26=arg[2]? arg[2][3] : 0;
  a27=(a26*a17);
  a25=(a25+a27);
  a13=(a09*a13);
  a13=(a14*a13);
  a13=(a13/a06);
  a25=(a25+a13);
  if (res[1]!=0) res[1][5]=a25;
  a25=arg[2]? arg[2][7] : 0;
  a15=(a25*a15);
  a13=arg[2]? arg[2][8] : 0;
  a17=(a13*a17);
  a15=(a15+a17);
  if (res[1]!=0) res[1][6]=a15;
  a15=(a04*a18);
  a15=(a02*a15);
  a17=(a01*a12);
  a27=(a05*a17);
  a15=(a15-a27);
  a27=(a02*a12);
  a28=(a08*a27);
  a29=(a07*a18);
  a29=(a01*a29);
  a28=(a28+a29);
  a15=(a15-a28);
  a12=(a12*a15);
  a27=(a04*a27);
  a28=(a18+a18);
  a28=(a10*a28);
  a27=(a27-a28);
  a17=(a07*a17);
  a27=(a27-a17);
  a17=(a18*a27);
  a12=(a12+a17);
  if (res[1]!=0) res[1][7]=a12;
  a12=(a16*a15);
  a17=(a20*a27);
  a12=(a12+a17);
  if (res[1]!=0) res[1][8]=a12;
  a12=(a19*a15);
  a17=(a22*a27);
  a12=(a12+a17);
  if (res[1]!=0) res[1][9]=a12;
  a12=(a21*a15);
  a17=(a24*a27);
  a12=(a12+a17);
  if (res[1]!=0) res[1][10]=a12;
  a12=(a23*a15);
  a17=(a26*a27);
  a12=(a12+a17);
  a18=(a09*a18);
  a18=(a14*a18);
  a18=(a18/a06);
  a12=(a12+a18);
  if (res[1]!=0) res[1][11]=a12;
  a15=(a25*a15);
  a27=(a13*a27);
  a15=(a15+a27);
  if (res[1]!=0) res[1][12]=a15;
  a15=(a04*a20);
  a15=(a02*a15);
  a27=(a01*a16);
  a12=(a05*a27);
  a15=(a15-a12);
  a12=(a02*a16);
  a18=(a08*a12);
  a17=(a07*a20);
  a17=(a01*a17);
  a18=(a18+a17);
  a15=(a15-a18);
  a16=(a16*a15);
  a12=(a04*a12);
  a18=(a20+a20);
  a18=(a10*a18);
  a12=(a12-a18);
  a27=(a07*a27);
  a12=(a12-a27);
  a27=(a20*a12);
  a16=(a16+a27);
  if (res[1]!=0) res[1][13]=a16;
  a16=(a19*a15);
  a27=(a22*a12);
  a16=(a16+a27);
  if (res[1]!=0) res[1][14]=a16;
  a16=(a21*a15);
  a27=(a24*a12);
  a16=(a16+a27);
  if (res[1]!=0) res[1][15]=a16;
  a16=(a23*a15);
  a27=(a26*a12);
  a16=(a16+a27);
  a20=(a09*a20);
  a20=(a14*a20);
  a20=(a20/a06);
  a16=(a16+a20);
  if (res[1]!=0) res[1][16]=a16;
  a15=(a25*a15);
  a12=(a13*a12);
  a15=(a15+a12);
  if (res[1]!=0) res[1][17]=a15;
  a15=(a04*a22);
  a15=(a02*a15);
  a12=(a01*a19);
  a16=(a05*a12);
  a15=(a15-a16);
  a16=(a02*a19);
  a20=(a08*a16);
  a27=(a07*a22);
  a27=(a01*a27);
  a20=(a20+a27);
  a15=(a15-a20);
  a19=(a19*a15);
  a16=(a04*a16);
  a20=(a22+a22);
  a20=(a10*a20);
  a16=(a16-a20);
  a12=(a07*a12);
  a16=(a16-a12);
  a12=(a22*a16);
  a19=(a19+a12);
  if (res[1]!=0) res[1][18]=a19;
  a19=(a21*a15);
  a12=(a24*a16);
  a19=(a19+a12);
  if (res[1]!=0) res[1][19]=a19;
  a19=(a23*a15);
  a12=(a26*a16);
  a19=(a19+a12);
  a22=(a09*a22);
  a22=(a14*a22);
  a22=(a22/a06);
  a19=(a19+a22);
  if (res[1]!=0) res[1][20]=a19;
  a15=(a25*a15);
  a16=(a13*a16);
  a15=(a15+a16);
  if (res[1]!=0) res[1][21]=a15;
  a15=(a04*a24);
  a15=(a02*a15);
  a16=(a01*a21);
  a19=(a05*a16);
  a15=(a15-a19);
  a19=(a02*a21);
  a22=(a08*a19);
  a12=(a07*a24);
  a12=(a01*a12);
  a22=(a22+a12);
  a15=(a15-a22);
  a21=(a21*a15);
  a19=(a04*a19);
  a22=(a24+a24);
  a22=(a10*a22);
  a19=(a19-a22);
  a16=(a07*a16);
  a19=(a19-a16);
  a16=(a24*a19);
  a21=(a21+a16);
  if (res[1]!=0) res[1][22]=a21;
  a21=(a23*a15);
  a16=(a26*a19);
  a21=(a21+a16);
  a24=(a09*a24);
  a24=(a14*a24);
  a24=(a24/a06);
  a21=(a21+a24);
  if (res[1]!=0) res[1][23]=a21;
  a15=(a25*a15);
  a19=(a13*a19);
  a15=(a15+a19);
  if (res[1]!=0) res[1][24]=a15;
  a15=(a04*a26);
  a15=(a02*a15);
  a19=(a01*a23);
  a21=(a05*a19);
  a15=(a15-a21);
  a21=(a02*a23);
  a24=(a08*a21);
  a16=(a07*a26);
  a16=(a01*a16);
  a24=(a24+a16);
  a15=(a15-a24);
  a23=(a23*a15);
  a24=(a14/a06);
  a24=(a09*a24);
  a16=(a26+a26);
  a16=(a10*a16);
  a24=(a24-a16);
  a21=(a04*a21);
  a24=(a24+a21);
  a19=(a07*a19);
  a24=(a24-a19);
  a19=(a26*a24);
  a23=(a23+a19);
  a09=(a09*a26);
  a14=(a14*a09);
  a14=(a14/a06);
  a03=(a03/a06);
  a00=(a00+a00);
  a11=sin(a11);
  a00=(a00*a11);
  a03=(a03*a00);
  a14=(a14+a03);
  a23=(a23+a14);
  if (res[1]!=0) res[1][25]=a23;
  a15=(a25*a15);
  a24=(a13*a24);
  a15=(a15+a24);
  if (res[1]!=0) res[1][26]=a15;
  a15=(a04*a13);
  a15=(a02*a15);
  a24=(a01*a25);
  a05=(a05*a24);
  a15=(a15-a05);
  a02=(a02*a25);
  a08=(a08*a02);
  a05=(a07*a13);
  a01=(a01*a05);
  a08=(a08+a01);
  a15=(a15-a08);
  a25=(a25*a15);
  a04=(a04*a02);
  a02=(a13+a13);
  a10=(a10*a02);
  a04=(a04-a10);
  a07=(a07*a24);
  a04=(a04-a07);
  a13=(a13*a04);
  a25=(a25+a13);
  if (res[1]!=0) res[1][27]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int spline_bicycle_model_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int spline_bicycle_model_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int spline_bicycle_model_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spline_bicycle_model_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int spline_bicycle_model_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void spline_bicycle_model_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void spline_bicycle_model_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void spline_bicycle_model_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int spline_bicycle_model_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int spline_bicycle_model_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real spline_bicycle_model_expl_ode_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spline_bicycle_model_expl_ode_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* spline_bicycle_model_expl_ode_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spline_bicycle_model_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* spline_bicycle_model_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int spline_bicycle_model_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int spline_bicycle_model_expl_ode_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
